from rdflib import Graph, Namespace, RDF

ontology_file_path = "files\\dishes.rdf"
g = Graph()
g.parse(ontology_file_path, format="xml")

food_ontology = Namespace("http://www.semanticweb.org/nevena/ontologies/2023/11/food_ontology.owl#")

dish_ingredients = {'chicken curry': ' ["onion", "tomato", "ginger", "garlic", "tomato puree", "chilli peppers", "turmeric", "cumin", "coriander", "cinnamon", "cardamom"]', 'ice cream': ' ["milk", "cream", "sweetener", "sugar", "alternative", "spice", "cocoa", "vanilla", "fruit", "stabilizers"]', 'moussaka': ' ["eggplant", "potato", "ground meat", "egg", "flour"]', 'kimchi': ' ["gochugaru", "spring onions", "garlic", "ginger", "jeotgal"]', 'sashimi': ' ["soy sauce"]', 'nachos': ' ["corn-", "wheat-based", "beef", "pork", "chicken", "seafood", "vegetables", "chesse"]', 'jambalaya': ' ["sausage", "pork", "chicken", "seafood", "crawfish", "shrimp", "onion", "celery", "green bell pepper", "okra", "carrots", "tomatoes", "corn", "chilis", "garlic"]', 'biryani': ' ["rice", "meat", "chicken", "beef", "goat", "lamb", "prawn", "fish", "spices", "vegetables"]', 'cordon bleu (dish)': ' ["meat", "cheese", "pork", "ham", "chicken"]', 'baklava': ' ["filo pastry", "nuts"]', 'verhackert': ' ["chopped bacon", "minced garlic", "salt", "sugar"]', 'cheesecake': ' ["cheese", "eggs", "sugar", "crushed cookies", "graham crackers", "pastry", "sponge cake"]', 'caesar salad': ' ["romaine lettuce", "lemon juice", "olive oil", "egg", "worcestershire sauce", "anchovies", "garlic", "dijon mustard", "parmesan cheese", "black pepper"]', 'pancakes': ' ["starch-based batter", "eggs", "milk", "butter", "oil"]', 'tiramisu': ' ["ladyfingers", "savoiardi", "coffee", "eggs", "sugar", "mascarpone", "cocoa"]', 'goulash': ' ["paprika"]', 'tomato puree': ' ["tomatoes"]', 'chilli peppers': ' []', 'cumin': ' []', 'coriander': ' []', 'cinnamon': ' []', 'cardamom': ' ["cardamom", "cardamon", "cardamum"]', 'cream': ' []', 'sweetener': ' []', 'sugar': ' ["sugar", "glucose", "fructose", "galactose", "sucrose", "lactose", "maltose"]', 'spice': ' []', 'vanilla': ' []', 'fruit': ' []', 'eggplant': ' []', 'potato': ' []', 'egg': ' []', 'gochugaru': ' []',
'spring onions': ' ["allium", "garlic", "shallot", "leek", "chive", "chinese onions"]', 'jeotgal': ' []', 'soy sauce': ' ["soybeans", "roasted grain", "brine", "aspergillus oryzae", "aspergillus sojae molds"]', 'corn-': ' []', 'wheat-based': ' ["wheat", "barley malt"]', 'beef': ' []', 'seafood': ' []', 'vegetables': ' []', 'chesse': ' ["proteins", "fat", "milk", "enzymes", "rennet", "bacterial enzymes"]', 'sausage': ' ["ground meat", "salt", "spices", "flavourings", "grains", "breadcrumbs"]', 'crawfish': ' []', 'shrimp': ' []', 'celery': ' []', 'green bell pepper': ' []', 'tomatoes': ' []', 'rice': ' []', 'goat': ' []', 'fish': ' []', 'cheese': ' []', 'filo pastry': ' ["oil", "butter"]', 'minced garlic': ' []', 'salt': ' []', 'eggs': ' []', 'graham crackers': ' ["graham flour"]', 'pastry': ' ["flour", "water", "shortening", "butter", "lard", "sugar", "milk", "baking powder", "eggs"]', 'romaine lettuce': ' ["romaine", "cos lettuce", "lactuca sativa l. var. longifolia", "lettuce"]', 'lemon juice': ' []', 'worcestershire sauce': ' []', 'anchovies': ' []', 'dijon mustard': ' ["vinegar", "verjuice", "unripe grapes", "mustard seeds", "white wine", "water", "salt"]', 'parmesan cheese': ' ["cows\' milk"]', 'oil': ' []', 'ladyfingers': ' ["egg"]', 'savoiardi': ' ["egg", "sugar syrup", "liqueur", "coffee", "espresso"]', 'coffee': ' ["roasted coffee beans", "caffeine", "coffea plant\'s fruits", "unroasted green coffee beans"]', 'mascarpone': ' ["cream", "whey"]', 'paprika': ' ["capsicum annuum varietals", "chili peppers"]', 'cilantro': ' []', 'essential oil': ' []', 'cinnamaldehyde': ' []', 'glucose': ' []', 'fructose': ' []', 'galactose': ' []', 'lactose': ' []', 'allium': ' []', 'shallot': ' []', 'leek': ' []', 'chive': ' []',
'chinese onions': ' []', 'soybeans': ' []', 'roasted grain': ' []', 'brine': ' []', 'aspergillus oryzae': ' []', 'aspergillus sojae molds': ' ["water", "salt"]', 'barley malt': ' ["sugar", "maltodextrines"]', 'proteins': ' []', 'fat': ' []', 'enzymes': ' []', 'bacterial enzymes': ' []', 'flavourings': ' ["sugars"]', 'grains': ' []', 'breadcrumbs': ' ["bread", "dry breads"]', 'shortening': ' ["shortening", "fat", "lard"]', 'lard': ' []', 'cos lettuce': ' []', 'vinegar': ' ["wine"]', 'verjuice': ' ["unripe grapes", "crab-apples", "herbs", "spices"]', 'mustard seeds': ' ["mustard seeds"]', "cows' milk": ' []', 'hydrocarbons': ' []', 'sugar syrup': ' ["inverted sugar syrup", "invert syrup", "invert sugar", "simple syrup", "sugar syrup", "sugar water", "bar syrup", "sucrose inversion", "table sugar"]', 'liqueur': ' ["grains", "fruits", "vegetables", "sugar"]', 'espresso': ' []', 'roasted coffee beans': ' ["coffee bean", "fruit", "pip", "coffee cherry", "cherry"]', 'unroasted green coffee beans': ' ["coffee bean", "pip"]', 'whey': ' []', 'capsicum annuum': ' ["paprika", "chili pepper", "jalape\\u00f1o", "cayenne", "bell pepper"]', 'chili peppers': ' []', 'cardamon': ' ["elettaria", "amomum"]', 'cardamum': ' ["cardamom"]', 'maltodextrines': ' ["maltodextrin"]', 'sugars': ' []', 'bread': ' []', 'wine': ' []', 'crab-apples': ' []', 'herbs': ' []', 'inverted sugar syrup': ' ["inverted sugar syrup", "invert syrup", "invert sugar", "simple syrup", "sugar syrup", "sugar water", "bar syrup", "sucrose inversion", "sucrose", "table sugar"]', 'invert syrup': ' ["inverted sugar syrup", "invert syrup", "invert sugar", "simple syrup", "sugar syrup", "sugar water", "bar syrup", "sucrose inversion", "sucrose", "table sugar"]', 'invert sugar': ' ["invert sugar"]',
'simple syrup': ' ["inverted sugar syrup", "invert syrup", "invert sugar", "simple syrup", "sugar syrup", "sugar water", "bar syrup", "sucrose inversion", "glucose", "fructose", "table sugar"]', 'sugar water': ' ["inverted sugar syrup", "invert syrup", "invert sugar", "simple syrup", "sugar syrup", "sugar water", "bar syrup", "sucrose inversion", "sucrose", "table sugar"]', 'bar syrup': ' ["inverted sugar syrup", "invert syrup", "invert sugar", "simple syrup", "sugar syrup", "sugar water", "bar syrup", "sucrose inversion", "sucrose", "table sugar"]', 'sucrose inversion': ' ["sucrose", "table sugar"]', 'table sugar': ' ["molasses", "sucrose"]', 'fruits': ' []', 'caffeine': ' []', "coffea plant's fruits": ' ["coffee beans"]', 'coffee bean': ' ["coffee bean"]', 'chili pepper': ' ["capsaicin"]', 'jalapeño': ' []', 'cayenne': ' []', 'capsaicin': ' ["capsaicin", "capsaicinoids"]', 'capsaicinoids': ' []', 'elettaria': ' []', 'amomum': ' []', 'maltodextrin': ' ["maltodextrin"]', 'molasses': ' []', 'coffee cherry': ' []', 'cherry': ' []', 'coffee beans': ' ["coffee bean", "pip"]', '8-methyl-n-vanillyl-6-nonenamide': ' []', 'monosaccharides': ' ["monosaccharides", "simple sugars", "carbohydrates"]', 'disaccharide sucrose': ' []', 'sugarcane molasses': ' ["molasses"]', 'berries': ' []', 'simple sugars': ' []', 'carbohydrates': ' []', 'sugarcane': ' ["sucrose"]', 'sugar beet juice': ' ["sucrose"]'}


# pretpostavljamo  da je svaki sastojak koji je sa desne strane vec ubacen
for maybe_dish, ingredients in dish_ingredients.items():
    dish_individual = food_ontology[maybe_dish.replace(" ", "_").lower()]
    for ingredient in eval(ingredients):
        ingredient_individual = food_ontology[ingredient.replace(" ", "_").lower()]
        g.add((ingredient_individual, RDF.type, food_ontology.Ingredient))
        g.add((dish_individual, food_ontology.hasIngredient, ingredient_individual))

g.serialize(destination="files\\ingredients.rdf", format="xml")
